// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Thvht05uRQLS8icbp1p4cHqpDPcOfwM',
    appId: '1:1007955029966:web:ce4a85b217a72ddafec59f',
    messagingSenderId: '1007955029966',
    projectId: 'halalxperience',
    authDomain: 'halalxperience.firebaseapp.com',
    storageBucket: 'halalxperience.appspot.com',
    measurementId: 'G-ZE5PMVKLEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PeZqyZn--yhSCb1XXj3ax0bEdFwyOL0',
    appId: '1:1007955029966:android:14238ac63f1941cafec59f',
    messagingSenderId: '1007955029966',
    projectId: 'halalxperience',
    storageBucket: 'halalxperience.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-RumbD8LDc41EXQUpVJvblR3atbF37M4',
    appId: '1:1007955029966:ios:7af9cac0b2015a3bfec59f',
    messagingSenderId: '1007955029966',
    projectId: 'halalxperience',
    storageBucket: 'halalxperience.appspot.com',
    iosClientId: '1007955029966-2657lats91gofqiqmh3vhroskm2ve0hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalxperience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-RumbD8LDc41EXQUpVJvblR3atbF37M4',
    appId: '1:1007955029966:ios:7af9cac0b2015a3bfec59f',
    messagingSenderId: '1007955029966',
    projectId: 'halalxperience',
    storageBucket: 'halalxperience.appspot.com',
    iosClientId: '1007955029966-2657lats91gofqiqmh3vhroskm2ve0hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalxperience',
  );
}
